name: CI

on:
  push:
    branches: [ .* ]
  pull_request:
    branches: [ main, release, development ]
    
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Build
        run: echo Building...
        
  verify-build:
    
    runs-on: ubuntu-latest
    needs: build    
    steps:
      
      - uses: actions/checkout@v2
      - name: Unit Tests
        run: echo unit tests runing...
      - name: Code Quality
        run: echo Scaning SonarQube...
        
  
